project:
  type: website
  output-dir: docs
  
website:
  title: "Cardiff Fungal Ecology Group"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: SRPproject.qmd
        text: Find Our Fungi!
       
  site-url: "https://fungalecology.com"
  repo-url: "https://github.com/ecologysarah/FungalEcologyWebsite"
  repo-actions: [edit, issue]  # Adds edit/issue links

format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    
editor: source

