---
title: "About us"
---

The Cardiff fungi group started out in 1986, when Lynne Boddy arrived at what was then University of Wales College, Cardiff. Over time, UWCC became Cardiff University, and the fungi research group moved around different campus locations until finally settling on the sixth floor of the Sir Martin Evans Building. The group has been composed of an ever-changing kaleidoscope of postdocs, technicians PhD students, master's students and undergraduates. Many of those who joined the group in one role have stayed on to take up another; technicians and master's students have become PhD students, and PhD students have become postdocs. 

In 2023, a former PhD student, Sarah Christofides, gained a lectureship at the School of Biosciences and rejoined the group to co-lead it alongside Lynne. Lynne and Sarah have worked together for many years and provide complementary skills and experience which have allowed the group to go from strength to strength. As a group, we pride ourselves on being an exceptionally friendly and supportive team, where is member is valued as an individual and where helping each other is our *modus operandi*. Team lunch breaks, regular inclusive socials and a collective silly sense of humour all help foster a sense of team identity where everyone is welcome.